<?php if (!empty($this->error)) : ?>
    <p style="color:red;"><?= $this->escapeHtml($this->error) ?></p>
<?php else : ?>
    <label for="layoutSelect">Layout:</label>
    <select id="layoutSelect">
        <option value="preset">Custom (Lookup)</option>
        <option value="breadthfirst">Breadthfirst</option>
        <option value="grid">Grid</option>
        <option value="circle">Circle</option>
        <option value="concentric">Concentric</option>
        <!-- excluded for performance issues -->
        <!-- <option value="cose">COSE</option> -->

    </select>

    <div id="cy" style="width: 100%; height: 800px;"></div>

    <script src="https://unpkg.com/cytoscape/dist/cytoscape.min.js"></script>
    <script>
    const cyNodes = <?= json_encode($this->cyNodes) ?>;
    const cyEdges = <?= json_encode($this->cyEdges) ?>;
    const rootId = <?= json_encode($this->rootId) ?>;

    const cy = cytoscape({
        container: document.getElementById('cy'),
        elements: { nodes: cyNodes, edges: cyEdges },
        style: [
            {
                selector: 'node',
                style: {
                    'label': 'data(label)',
                    'background-color': '#0074D9',
                    'width': 20,
                    'height': 20,
                    'font-size': 8
                }
            },
            {
                selector: 'edge',
                style: {
                    'width': 1,
                    'line-color': '#ccc'
                }
            }
        ],
        layout: { name: 'preset', animate: false }
    });

    // Highlight the root node
    cy.$(`#${rootId}`).style('background-color', 'red');

    document.getElementById('layoutSelect').addEventListener('change', function () {
    const layoutName = this.value;

    const layout = cy.layout({
        name: layoutName,
        animate: false
    });

    layout.run();
});
    </script>
<?php endif; ?>
